### ISSUE TITLE
Build failure with multiple versions of rand

### ISSUE THREAD

**Issue by dekellum** [flier/rust-fasthash#6]
With the release of extprim crate, 1.5.0+ builds are failing with:

~~~
error[E0277]: the trait bound `extprim::u128::u128: rand::Rand` is not satisfied
~~~

The extprim 1.5.0 and 1.5.1 crates have rand crate as a dependency, updated to ^0.4.  Oddly enough, rather than leaving extprim < 1.5.0, cargo is importing both rand 0.3.x and rand 0.4.x which fails to compile with the errors indicated.  Unless that behavior makes sense to someone, I might also site this issue in a companion issue with cargo.

Simply updating fasthash crates dependency to rand ^0.4 results in a slightly different error, since xoroshiro128 has it own rand dependency.  I have a workaround I will submit in a PR shortly.

Note that same issue also applies to users of the fasthash crate, which is how I encountered this in the first place.

**Comment by dekellum** [comment]
Note that a similar workaround is available to current consumers of the fasthash crate (e.g. 0.2.6). In a currently private project I have these deps in Cargo.toml:

~~~ toml
fasthash =       ">=0.2, <2.0"
extprim =        "~1.4.0" # constrain fasthash to avoid two rand versions
~~~

**Comment by flier** [comment]
agree, I have submitted a [PR](https://github.com/mscharley/rust-xoroshiro128/pull/6) to upstream [rust-xoroshiro128](https://github.com/mscharley/rust-xoroshiro128), and use [upgrade-rand](https://github.com/flier/rust-fasthash/tree/upgrade-rand) branch to trace it.

**Comment by flier** [comment]
please check 0.2.8, thanks
